version: "3.9"

services:
  backend:
    build: flask
    restart: always
    volumes:
      - ./flask:/app
    stdin_open: true # enable attach for pdb
    ports:
      - '8000:80'

  frontend:
    build: react
    restart: always
    depends_on:
      - backend
    volumes:
      - ./react:/frontend
    ports:
      - "8090:80"
